[package]
name = "sdv-macro"
version = "0.1.0"
edition = "2021"


[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.79"
quote = "1.0.35"
sdv-core = { path = "../sdv-core" }
syn = { version = "2.0.53", features = ["extra-traits"] }
