use std::convert::{TryFrom, TryInto};

use anyhow::Result;
use roxmltree::Node;

use super::{Finder, NodeFinder};

#[derive(Debug)]
pub struct Stats {
    pub seeds_sown: u32,
    pub items_shipped: u32,
    pub items_cooked: u32,
    pub items_crafted: u32,
    pub chicken_eggs_layed: u32,
    pub duck_eggs_layed: u32,
    pub cow_milk_produced: u32,
    pub goat_milk_produced: u32,
    pub rabbit_wool_produced: u32,
    pub sheep_wool_produced: u32,
    pub cheese_made: u32,
    pub goat_cheese_made: u32,
    pub truffles_found: u32,
    pub stone_gathered: u32,
    pub rocks_crushed: u32,
    pub dirt_hoed: u32,
    pub gifts_given: u32,
    pub times_unconscious: u32,
    pub average_bedtime: u32,
    pub times_fished: u32,
    pub fish_caught: u32,
    pub boulders_cracked: u32,
    pub stumps_chopped: u32,
    pub steps_taken: u32,
    pub monsters_killed: u32,
    pub diamonds_found: u32,
    pub prismatic_shards_found: u32,
    pub other_precious_gems_found: u32,
    pub cave_carrots_found: u32,
    pub copper_found: u32,
    pub iron_found: u32,
    pub coal_found: u32,
    pub coins_found: u32,
    pub gold_found: u32,
    pub iridium_found: u32,
    pub bars_smelted: u32,
    pub beverages_made: u32,
    pub preserves_made: u32,
    pub pieces_of_trash_recycled: u32,
    pub mystic_stones_crushed: u32,
    pub days_played: u32,
    pub weeds_eliminated: u32,
    pub sticks_chopped: u32,
    pub notes_found: u32,
    pub quests_completed: u32,
    pub star_level_crops_shipped: u32,
    pub crops_shipped: u32,
    pub items_foraged: u32,
    pub slimes_killed: u32,
    pub geodes_cracked: u32,
    pub good_friends: u32,
    pub total_money_gifted: u32,
    pub individual_money_earned: u32,
}

impl Stats {
    fn from_node(node: Node) -> Result<Stats> {
        Ok(Stats {
            seeds_sown: node.child("seedsSown").try_into()?,
            items_shipped: node.child("itemsShipped").try_into()?,
            items_cooked: node.child("itemsCooked").try_into()?,
            items_crafted: node.child("itemsCrafted").try_into()?,
            chicken_eggs_layed: node.child("chickenEggsLayed").try_into()?,
            duck_eggs_layed: node.child("duckEggsLayed").try_into()?,
            cow_milk_produced: node.child("cowMilkProduced").try_into()?,
            goat_milk_produced: node.child("goatMilkProduced").try_into()?,
            rabbit_wool_produced: node.child("rabbitWoolProduced").try_into()?,
            sheep_wool_produced: node.child("sheepWoolProduced").try_into()?,
            cheese_made: node.child("cheeseMade").try_into()?,
            goat_cheese_made: node.child("goatCheeseMade").try_into()?,
            truffles_found: node.child("trufflesFound").try_into()?,
            stone_gathered: node.child("stoneGathered").try_into()?,
            rocks_crushed: node.child("rocksCrushed").try_into()?,
            dirt_hoed: node.child("dirtHoed").try_into()?,
            gifts_given: node.child("giftsGiven").try_into()?,
            times_unconscious: node.child("timesUnconscious").try_into()?,
            average_bedtime: node.child("averageBedtime").try_into()?,
            times_fished: node.child("timesFished").try_into()?,
            fish_caught: node.child("fishCaught").try_into()?,
            boulders_cracked: node.child("bouldersCracked").try_into()?,
            stumps_chopped: node.child("stumpsChopped").try_into()?,
            steps_taken: node.child("stepsTaken").try_into()?,
            monsters_killed: node.child("monstersKilled").try_into()?,
            diamonds_found: node.child("diamondsFound").try_into()?,
            prismatic_shards_found: node.child("prismaticShardsFound").try_into()?,
            other_precious_gems_found: node.child("otherPreciousGemsFound").try_into()?,
            cave_carrots_found: node.child("caveCarrotsFound").try_into()?,
            copper_found: node.child("copperFound").try_into()?,
            iron_found: node.child("ironFound").try_into()?,
            coal_found: node.child("coalFound").try_into()?,
            coins_found: node.child("coinsFound").try_into()?,
            gold_found: node.child("goldFound").try_into()?,
            iridium_found: node.child("iridiumFound").try_into()?,
            bars_smelted: node.child("barsSmelted").try_into()?,
            beverages_made: node.child("beveragesMade").try_into()?,
            preserves_made: node.child("preservesMade").try_into()?,
            pieces_of_trash_recycled: node.child("piecesOfTrashRecycled").try_into()?,
            mystic_stones_crushed: node.child("mysticStonesCrushed").try_into()?,
            days_played: node.child("daysPlayed").try_into()?,
            weeds_eliminated: node.child("weedsEliminated").try_into()?,
            sticks_chopped: node.child("sticksChopped").try_into()?,
            notes_found: node.child("notesFound").try_into()?,
            quests_completed: node.child("questsCompleted").try_into()?,
            star_level_crops_shipped: node.child("starLevelCropsShipped").try_into()?,
            crops_shipped: node.child("cropsShipped").try_into()?,
            items_foraged: node.child("itemsForaged").try_into()?,
            slimes_killed: node.child("slimesKilled").try_into()?,
            geodes_cracked: node.child("geodesCracked").try_into()?,
            good_friends: node.child("goodFriends").try_into()?,
            total_money_gifted: node.child("totalMoneyGifted").try_into()?,
            individual_money_earned: node.child("individualMoneyEarned").try_into()?,
        })
    }
}

impl<'a, 'input: 'a> TryFrom<NodeFinder<'a, 'input>> for Stats {
    type Error = anyhow::Error;
    fn try_from(finder: NodeFinder<'a, 'input>) -> Result<Self, Self::Error> {
        Self::from_node(finder.node()?)
    }
}
